In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('cricketdata.csv')

In [3]:
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,HC Brook (ENG),2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23
59,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
60,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
61,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
62,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

In [4]:
df = df.rename(columns = {'Mat':'Matches', 'NO':'Not_Outs', 'HS':'Highest_Inns_Score', 'BF':'Balls_Faced', 'SR':'Batting_Strike_Rate'})

In [5]:
df.head()

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,HC Brook (ENG),2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1

In [6]:
df.isnull().any()

Player                 False
Span                   False
Matches                False
Inns                   False
Not_Outs               False
Runs                   False
Highest_Inns_Score     False
Ave                    False
Balls_Faced             True
Batting_Strike_Rate     True
100                    False
50                     False
0                      False
4s                     False
6s                     False
dtype: bool

In [7]:
df[df['Balls_Faced'].isna()==1]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
9,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,NaN,NaN,15,19,6,258+,2
55,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,NaN,NaN,5,6,3,51+,0

In [8]:
df['Balls_Faced'] = df['Balls_Faced'].fillna(0)

In [9]:
df['Batting_Strike_Rate'] = df['Batting_Strike_Rate'].fillna(0)

In [10]:
df[df['Player']=='ED Weekes (WI)']

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
9,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,0,0.0,15,19,6,258+,2

In [11]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
58    False
59    False
60    False
61    False
62    False
Length: 63, dtype: bool

In [12]:
df[df['Player'].duplicated()==1]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
5,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
12,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+
15,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8
52,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26

In [13]:
df[df['Player'].isin(['GA Headley (WI)', 'GS Sobers (WI)', 'JB Hobbs (ENG)', 'V Kohli (IND)'])]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
5,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
11,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+
12,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+
14,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8
15,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8
51,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26
52,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26

In [14]:
df = df.drop_duplicates()

In [15]:
df[df['Player'].isin(['GA Headley (WI)', 'GS Sobers (WI)', 'JB Hobbs (ENG)', 'V Kohli (IND)'])]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
11,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+
14,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8
51,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26

In [16]:
df['Span'].str.split(pat = '-')

0     [1928, 1948]
1     [2022, 2023]
2     [2015, 2016]
3     [1963, 1970]
4     [1930, 1954]
6     [1924, 1935]
7     [1931, 1939]
8     [1955, 1968]
9     [1948, 1958]
10    [1927, 1947]
11    [1954, 1974]
13    [2010, 2024]
14    [1908, 1930]
16    [1937, 1955]
17    [1995, 2013]
18    [1921, 1929]
19    [2010, 2024]
20    [1968, 1973]
21    [1993, 1995]
22    [1970, 1984]
23    [1935, 1951]
24    [1989, 2013]
25    [1990, 2006]
26    [1976, 1993]
27    [1996, 2012]
28    [1998, 2010]
29    [2000, 2017]
30    [1995, 2012]
31    [1920, 1929]
32    [1992, 2002]
33    [2005, 2013]
34    [1994, 2015]
35    [1971, 1987]
36    [1985, 2004]
37    [1994, 2009]
38    [2004, 2018]
39    [1978, 1994]
40    [2019, 2024]
41    [1974, 1991]
42    [1937, 1957]
43    [1997, 2014]
44    [2012, 2024]
45    [1992, 2007]
46    [2018, 2024]
47    [1948, 1963]
48    [1911, 1928]
49    [2001, 2013]
50    [2019, 2021]
51    [2011, 2024]
53    [1961, 1966]
54    [1929, 1949]
55    [1893, 1905]
56    [2001, 2013]
57    [1948, 1963]
58    [1965, 1981]
59    [2002, 2014]
60    [1924, 1934]
61    [1930, 1938]
62    [1928, 1934]
Name: Span, dtype: object

In [17]:
df['Span'].str.split(pat = '-').str[0]

0     1928
1     2022
2     2015
3     1963
4     1930
6     1924
7     1931
8     1955
9     1948
10    1927
11    1954
13    2010
14    1908
16    1937
17    1995
18    1921
19    2010
20    1968
21    1993
22    1970
23    1935
24    1989
25    1990
26    1976
27    1996
28    1998
29    2000
30    1995
31    1920
32    1992
33    2005
34    1994
35    1971
36    1985
37    1994
38    2004
39    1978
40    2019
41    1974
42    1937
43    1997
44    2012
45    1992
46    2018
47    1948
48    1911
49    2001
50    2019
51    2011
53    1961
54    1929
55    1893
56    2001
57    1948
58    1965
59    2002
60    1924
61    1930
62    1928
Name: Span, dtype: object

In [18]:
df['Rookie_Year'] = df['Span'].str.split(pat = '-').str[0]

In [19]:
df['Final_Year'] = df['Span'].str.split(pat = '-').str[1]

In [20]:
df

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948
1,HC Brook (ENG),2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954
6,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935
7,E Paynter (ENG),1931-1939,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4,1931,1939
8,KF Barrington (ENG),1955-1968,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27,1955,1968
9,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,0,0.00,15,19,6,258+,2,1948,1958
10,WR Hammond (ENG),1927-1947,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419+,27,1927,1947
11,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+,1954,1974
13,SPD Smith (AUS),2010-2024,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024
14,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8,1908,1930
16,L Hutton (ENG),1937-1955,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358+,7,1937,1955
17,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013
18,GE Tyldesley (ENG),1921-1929,14,20,2,990,122,55.00,178+,29.21,3,6,2,37+,2,1921,1929
19,KS Williamson (NZ),2010-2024,100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24,2010,2024
20,CA Davis (WI),1968-1973,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65+,1,1968,1973
21,VG Kambli (IND),1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995
22,GS Chappell (AUS),1970-1984,87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16,1970,1984
23,AD Nourse (SA),1935-1951,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115+,6,1935,1951
24,SR Tendulkar (IND),1989-2013,200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058+,69,1989,2013
25,BC Lara (ICC/WI),1990-2006,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88,1990,2006
26,Javed Miandad (PAK),1976-1993,124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788+,48,1976,1993
27,R Dravid (ICC/IND),1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012
28,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010
29,Younis Khan (PAK),2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017
30,RT Ponting (AUS),1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012
31,J Ryder (AUS),1920-1929,20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102+,3,1920,1929
32,A Flower (ZIM),1992-2002,63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20,1992,2002
33,MEK Hussey (AUS),2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013
34,S Chanderpaul (WI),1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36,1994,2015
35,SM Gavaskar (IND),1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908+,26,1971,1987
36,SR Waugh (AUS),1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004
37,ML Hayden (AUS),1994-2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009
38,AB de Villiers (SA),2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64,2004,2018
39,AR Border (AUS),1978-1994,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994
40,DJ Mitchell (NZ),2019-2024,23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29,2019,2024
41,IVA Richards (WI),1974-1991,121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952+,84,1974,1991
42,DCS Compton (ENG),1937-1957,78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342+,3,1937,1957
43,DPMD Jayawardene (SL),1997-2014,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014
44,JE Root (ENG),2012-2024,140,257,21,11736,254,49.72,20762,56.52,31,61,12,1280,44,2012,2024
45,Inzamam-ul-Haq (ICC/PAK),1992-2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007
46,M Labuschagne (AUS),2018-2024,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024
47,FMM Worrell (WI),1948-1963,51,87,9,3860,261,49.48,488+,40.16,9,22,11,240+,11,1948,1963
48,CP Mead (ENG),1911-1928,17,26,2,1185,182*,49.37,619+,30.04,4,3,3,38+,0,1911,1928
49,V Sehwag (ICC/IND),2001-2013,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013
50,Abid Ali (PAK),2019-2021,16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5,2019,2021
51,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26,2011,2024
53,KC Bland (SA),1961-1966,21,39,5,1669,144*,49.08,885+,37.74,3,9,2,123+,20,1961,1966
54,B Mitchell (SA),1929-1949,42,80,9,3471,189*,48.88,158+,29.11,8,21,3,41+,1,1929,1949
55,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,0,0.00,5,6,3,51+,0,1893,1905
56,TT Samaraweera (SL),2001-2013,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013
57,RN Harvey (AUS),1948-1963,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427+,1,1948,1963
58,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981
59,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014
60,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934
61,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938
62,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934

In [21]:
df.drop(['Span'], axis = 1)

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948
1,HC Brook (ENG),12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023
2,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
3,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970
4,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954
6,H Sutcliffe (ENG),54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935
7,E Paynter (ENG),20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4,1931,1939
8,KF Barrington (ENG),82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27,1955,1968
9,ED Weekes (WI),48,81,5,4455,207,58.61,0,0.00,15,19,6,258+,2,1948,1958
10,WR Hammond (ENG),85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419+,27,1927,1947
11,GS Sobers (WI),93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+,1954,1974
13,SPD Smith (AUS),109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024
14,JB Hobbs (ENG),61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8,1908,1930
16,L Hutton (ENG),79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358+,7,1937,1955
17,JH Kallis (ICC/SA),166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013
18,GE Tyldesley (ENG),14,20,2,990,122,55.00,178+,29.21,3,6,2,37+,2,1921,1929
19,KS Williamson (NZ),100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24,2010,2024
20,CA Davis (WI),15,29,5,1301,183,54.20,665+,35.48,4,4,1,65+,1,1968,1973
21,VG Kambli (IND),17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995
22,GS Chappell (AUS),87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16,1970,1984
23,AD Nourse (SA),34,62,7,2960,231,53.81,108+,63.88,9,14,3,115+,6,1935,1951
24,SR Tendulkar (IND),200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058+,69,1989,2013
25,BC Lara (ICC/WI),131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88,1990,2006
26,Javed Miandad (PAK),124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788+,48,1976,1993
27,R Dravid (ICC/IND),164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012
28,Mohammad Yousuf (PAK),90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010
29,Younis Khan (PAK),118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017
30,RT Ponting (AUS),168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012
31,J Ryder (AUS),20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102+,3,1920,1929
32,A Flower (ZIM),63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20,1992,2002
33,MEK Hussey (AUS),79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013
34,S Chanderpaul (WI),164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36,1994,2015
35,SM Gavaskar (IND),125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908+,26,1971,1987
36,SR Waugh (AUS),168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004
37,ML Hayden (AUS),103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009
38,AB de Villiers (SA),114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64,2004,2018
39,AR Border (AUS),156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994
40,DJ Mitchell (NZ),23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29,2019,2024
41,IVA Richards (WI),121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952+,84,1974,1991
42,DCS Compton (ENG),78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342+,3,1937,1957
43,DPMD Jayawardene (SL),149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014
44,JE Root (ENG),140,257,21,11736,254,49.72,20762,56.52,31,61,12,1280,44,2012,2024
45,Inzamam-ul-Haq (ICC/PAK),120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007
46,M Labuschagne (AUS),50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024
47,FMM Worrell (WI),51,87,9,3860,261,49.48,488+,40.16,9,22,11,240+,11,1948,1963
48,CP Mead (ENG),17,26,2,1185,182*,49.37,619+,30.04,4,3,3,38+,0,1911,1928
49,V Sehwag (ICC/IND),104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013
50,Abid Ali (PAK),16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5,2019,2021
51,V Kohli (IND),113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26,2011,2024
53,KC Bland (SA),21,39,5,1669,144*,49.08,885+,37.74,3,9,2,123+,20,1961,1966
54,B Mitchell (SA),42,80,9,3471,189*,48.88,158+,29.11,8,21,3,41+,1,1929,1949
55,Hon.FS Jackson (ENG),20,33,4,1415,144*,48.79,0,0.00,5,6,3,51+,0,1893,1905
56,TT Samaraweera (SL),81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013
57,RN Harvey (AUS),79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427+,1,1948,1963
58,KD Walters (AUS),74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981
59,GC Smith (ICC/SA),117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014
60,WH Ponsford (AUS),29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934
61,SJ McCabe (AUS),39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938
62,DR Jardine (ENG),22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934

In [22]:
df['Player'].str.split(pat = '(')

0             [DG Bradman , AUS)]
1               [HC Brook , ENG)]
2               [AC Voges , AUS)]
3              [RG Pollock , SA)]
4              [GA Headley , WI)]
6            [H Sutcliffe , ENG)]
7              [E Paynter , ENG)]
8          [KF Barrington , ENG)]
9               [ED Weekes , WI)]
10            [WR Hammond , ENG)]
11              [GS Sobers , WI)]
13             [SPD Smith , AUS)]
14              [JB Hobbs , ENG)]
16              [L Hutton , ENG)]
17          [JH Kallis , ICC/SA)]
18          [GE Tyldesley , ENG)]
19          [KS Williamson , NZ)]
20               [CA Davis , WI)]
21             [VG Kambli , IND)]
22           [GS Chappell , AUS)]
23              [AD Nourse , SA)]
24          [SR Tendulkar , IND)]
25            [BC Lara , ICC/WI)]
26         [Javed Miandad , PAK)]
27          [R Dravid , ICC/IND)]
28       [Mohammad Yousuf , PAK)]
29           [Younis Khan , PAK)]
30            [RT Ponting , AUS)]
31               [J Ryder , AUS)]
32              [A Flower , ZIM)]
33            [MEK Hussey , AUS)]
34          [S Chanderpaul , WI)]
35           [SM Gavaskar , IND)]
36              [SR Waugh , AUS)]
37             [ML Hayden , AUS)]
38         [AB de Villiers , SA)]
39             [AR Border , AUS)]
40            [DJ Mitchell , NZ)]
41           [IVA Richards , WI)]
42           [DCS Compton , ENG)]
43       [DPMD Jayawardene , SL)]
44               [JE Root , ENG)]
45    [Inzamam-ul-Haq , ICC/PAK)]
46         [M Labuschagne , AUS)]
47            [FMM Worrell , WI)]
48               [CP Mead , ENG)]
49          [V Sehwag , ICC/IND)]
50              [Abid Ali , PAK)]
51               [V Kohli , IND)]
53               [KC Bland , SA)]
54             [B Mitchell , SA)]
55        [Hon.FS Jackson , ENG)]
56         [TT Samaraweera , SL)]
57             [RN Harvey , AUS)]
58            [KD Walters , AUS)]
59           [GC Smith , ICC/SA)]
60           [WH Ponsford , AUS)]
61             [SJ McCabe , AUS)]
62            [DR Jardine , ENG)]
Name: Player, dtype: object

In [23]:
df['Country'] = df['Player'].str.split(pat = '(').str[1]

In [24]:
df['Country'] = df['Country'].str.split(pat = ')').str[0]

In [25]:
df['Country']

0         AUS
1         ENG
2         AUS
3          SA
4          WI
6         ENG
7         ENG
8         ENG
9          WI
10        ENG
11         WI
13        AUS
14        ENG
16        ENG
17     ICC/SA
18        ENG
19         NZ
20         WI
21        IND
22        AUS
23         SA
24        IND
25     ICC/WI
26        PAK
27    ICC/IND
28        PAK
29        PAK
30        AUS
31        AUS
32        ZIM
33        AUS
34         WI
35        IND
36        AUS
37        AUS
38         SA
39        AUS
40         NZ
41         WI
42        ENG
43         SL
44        ENG
45    ICC/PAK
46        AUS
47         WI
48        ENG
49    ICC/IND
50        PAK
51        IND
53         SA
54         SA
55        ENG
56         SL
57        AUS
58        AUS
59     ICC/SA
60        AUS
61        AUS
62        ENG
Name: Country, dtype: object

In [26]:
df['Player'] = df['Player'].str.split(pat = '(').str[0]

In [27]:
df.head()

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country
0,DG Bradman,1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,AUS
1,HC Brook,2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023,ENG
2,AC Voges,2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
3,RG Pollock,1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA
4,GA Headley,1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954,WI

In [28]:
df.dtypes

Player                  object
Span                    object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                     int64
Highest_Inns_Score      object
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Rookie_Year             object
Final_Year              object
Country                 object
dtype: object

In [29]:
df['Highest_Inns_Score'].str.split(pat = '*').str[0]

0     334
1     186
2     269
3     274
4     270
6     194
7     243
8     256
9     207
10    336
11    365
13    239
14    211
16    364
17    224
18    122
19    251
20    183
21    227
22    247
23    231
24    248
25    400
26    280
27    270
28    223
29    313
30    257
31    201
32    232
33    195
34    203
35    236
36    200
37    380
38    278
39    205
40    190
41    291
42    278
43    374
44    254
45    329
46    215
47    261
48    182
49    319
50    215
51    254
53    144
54    189
55    144
56    231
57    205
58    250
59    277
60    266
61    232
62    127
Name: Highest_Inns_Score, dtype: object

In [30]:
df['Highest_Inns_Score'] = df['Highest_Inns_Score'].str.split(pat = '*').str[0]

In [31]:
df['Highest_Inns_Score'].astype('int')

0     334
1     186
2     269
3     274
4     270
6     194
7     243
8     256
9     207
10    336
11    365
13    239
14    211
16    364
17    224
18    122
19    251
20    183
21    227
22    247
23    231
24    248
25    400
26    280
27    270
28    223
29    313
30    257
31    201
32    232
33    195
34    203
35    236
36    200
37    380
38    278
39    205
40    190
41    291
42    278
43    374
44    254
45    329
46    215
47    261
48    182
49    319
50    215
51    254
53    144
54    189
55    144
56    231
57    205
58    250
59    277
60    266
61    232
62    127
Name: Highest_Inns_Score, dtype: int32

In [32]:
df['Highest_Inns_Score'] = df['Highest_Inns_Score'].astype('int')

In [33]:
df.dtypes

Player                  object
Span                    object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                     int64
Highest_Inns_Score       int32
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Rookie_Year             object
Final_Year              object
Country                 object
dtype: object

In [35]:
df = df.astype({'Rookie_Year':'int', 'Final_Year':'int'})

In [36]:
df.dtypes

Player                  object
Span                    object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                     int64
Highest_Inns_Score       int32
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Rookie_Year              int32
Final_Year               int32
Country                 object
dtype: object

In [37]:
df['Matches'] = df['Matches'].astype('int')

In [38]:
df.dtypes

Player                  object
Span                    object
Matches                  int32
Inns                     int64
Not_Outs                 int64
Runs                     int64
Highest_Inns_Score       int32
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Rookie_Year              int32
Final_Year               int32
Country                 object
dtype: object

In [39]:
df['Balls_Faced'] = df['Balls_Faced'].str.split(pat = '+').str[0]

In [54]:
df

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country
0,DG Bradman,1928-1948,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626+,6,1928,1948,AUS
1,HC Brook,2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023,ENG
2,AC Voges,2015-2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
3,RG Pollock,1963-1970,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246+,11,1963,1970,SA
4,GA Headley,1930-1954,22,40,4,2190,270,60.83,416,56.00,10,5,2,104+,1,1930,1954,WI
6,H Sutcliffe,1924-1935,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202+,6,1924,1935,ENG
7,E Paynter,1931-1939,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125+,4,1931,1939,ENG
8,KF Barrington,1955-1968,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591+,27,1955,1968,ENG
9,ED Weekes,1948-1958,48,81,5,4455,207,58.61,NaN,0.00,15,19,6,258+,2,1948,1958,WI
10,WR Hammond,1927-1947,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419+,27,1927,1947,ENG
11,GS Sobers,1954-1974,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593+,32+,1954,1974,WI
13,SPD Smith,2010-2024,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024,AUS
14,JB Hobbs,1908-1930,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276+,8,1908,1930,ENG
16,L Hutton,1937-1955,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358+,7,1937,1955,ENG
17,JH Kallis,1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,ICC/SA
18,GE Tyldesley,1921-1929,14,20,2,990,122,55.00,178,29.21,3,6,2,37+,2,1921,1929,ENG
19,KS Williamson,2010-2024,100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24,2010,2024,NZ
20,CA Davis,1968-1973,15,29,5,1301,183,54.20,665,35.48,4,4,1,65+,1,1968,1973,WI
21,VG Kambli,1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,IND
22,GS Chappell,1970-1984,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,1970,1984,AUS
23,AD Nourse,1935-1951,34,62,7,2960,231,53.81,108,63.88,9,14,3,115+,6,1935,1951,SA
24,SR Tendulkar,1989-2013,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058+,69,1989,2013,IND
25,BC Lara,1990-2006,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006,ICC/WI
26,Javed Miandad,1976-1993,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788+,48,1976,1993,PAK
27,R Dravid,1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,ICC/IND
28,Mohammad Yousuf,1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,PAK
29,Younis Khan,2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,PAK
30,RT Ponting,1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,AUS
31,J Ryder,1920-1929,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102+,3,1920,1929,AUS
32,A Flower,1992-2002,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,1992,2002,ZIM
33,MEK Hussey,2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,AUS
34,S Chanderpaul,1994-2015,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015,WI
35,SM Gavaskar,1971-1987,125,214,16,10122,236,51.12,14184,43.35,34,45,12,908+,26,1971,1987,IND
36,SR Waugh,1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,AUS
37,ML Hayden,1994-2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,AUS
38,AB de Villiers,2004-2018,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,SA
39,AR Border,1978-1994,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,1978,1994,AUS
40,DJ Mitchell,2019-2024,23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29,2019,2024,NZ
41,IVA Richards,1974-1991,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952+,84,1974,1991,WI
42,DCS Compton,1937-1957,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342+,3,1937,1957,ENG
43,DPMD Jayawardene,1997-2014,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,SL
44,JE Root,2012-2024,140,257,21,11736,254,49.72,20762,56.52,31,61,12,1280,44,2012,2024,ENG
45,Inzamam-ul-Haq,1992-2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,ICC/PAK
46,M Labuschagne,2018-2024,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024,AUS
47,FMM Worrell,1948-1963,51,87,9,3860,261,49.48,488,40.16,9,22,11,240+,11,1948,1963,WI
48,CP Mead,1911-1928,17,26,2,1185,182,49.37,619,30.04,4,3,3,38+,0,1911,1928,ENG
49,V Sehwag,2001-2013,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,ICC/IND
50,Abid Ali,2019-2021,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,2019,2021,PAK
51,V Kohli,2011-2024,113,191,11,8848,254,49.15,15924,55.56,29,30,14,991,26,2011,2024,IND
53,KC Bland,1961-1966,21,39,5,1669,144,49.08,885,37.74,3,9,2,123+,20,1961,1966,SA
54,B Mitchell,1929-1949,42,80,9,3471,189,48.88,158,29.11,8,21,3,41+,1,1929,1949,SA
56,TT Samaraweera,2001-2013,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,SL
57,RN Harvey,1948-1963,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427+,1,1948,1963,AUS
58,KD Walters,1965-1981,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525+,23,1965,1981,AUS
59,GC Smith,2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA
60,WH Ponsford,1924-1934,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119+,0,1924,1934,AUS
61,SJ McCabe,1930-1938,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241+,5+,1930,1938,AUS
62,DR Jardine,1928-1934,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53+,0,1928,1934,ENG

In [55]:
df = df.drop(9, axis = 0)

In [56]:
df

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country
0,DG Bradman,1928-1948,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626+,6,1928,1948,AUS
1,HC Brook,2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023,ENG
2,AC Voges,2015-2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
3,RG Pollock,1963-1970,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246+,11,1963,1970,SA
4,GA Headley,1930-1954,22,40,4,2190,270,60.83,416,56.00,10,5,2,104+,1,1930,1954,WI
6,H Sutcliffe,1924-1935,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202+,6,1924,1935,ENG
7,E Paynter,1931-1939,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125+,4,1931,1939,ENG
8,KF Barrington,1955-1968,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591+,27,1955,1968,ENG
10,WR Hammond,1927-1947,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419+,27,1927,1947,ENG
11,GS Sobers,1954-1974,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593+,32+,1954,1974,WI
13,SPD Smith,2010-2024,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024,AUS
14,JB Hobbs,1908-1930,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276+,8,1908,1930,ENG
16,L Hutton,1937-1955,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358+,7,1937,1955,ENG
17,JH Kallis,1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,ICC/SA
18,GE Tyldesley,1921-1929,14,20,2,990,122,55.00,178,29.21,3,6,2,37+,2,1921,1929,ENG
19,KS Williamson,2010-2024,100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24,2010,2024,NZ
20,CA Davis,1968-1973,15,29,5,1301,183,54.20,665,35.48,4,4,1,65+,1,1968,1973,WI
21,VG Kambli,1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,IND
22,GS Chappell,1970-1984,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,1970,1984,AUS
23,AD Nourse,1935-1951,34,62,7,2960,231,53.81,108,63.88,9,14,3,115+,6,1935,1951,SA
24,SR Tendulkar,1989-2013,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058+,69,1989,2013,IND
25,BC Lara,1990-2006,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006,ICC/WI
26,Javed Miandad,1976-1993,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788+,48,1976,1993,PAK
27,R Dravid,1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,ICC/IND
28,Mohammad Yousuf,1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,PAK
29,Younis Khan,2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,PAK
30,RT Ponting,1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,AUS
31,J Ryder,1920-1929,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102+,3,1920,1929,AUS
32,A Flower,1992-2002,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,1992,2002,ZIM
33,MEK Hussey,2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,AUS
34,S Chanderpaul,1994-2015,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015,WI
35,SM Gavaskar,1971-1987,125,214,16,10122,236,51.12,14184,43.35,34,45,12,908+,26,1971,1987,IND
36,SR Waugh,1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,AUS
37,ML Hayden,1994-2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,AUS
38,AB de Villiers,2004-2018,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,SA
39,AR Border,1978-1994,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,1978,1994,AUS
40,DJ Mitchell,2019-2024,23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29,2019,2024,NZ
41,IVA Richards,1974-1991,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952+,84,1974,1991,WI
42,DCS Compton,1937-1957,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342+,3,1937,1957,ENG
43,DPMD Jayawardene,1997-2014,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,SL
44,JE Root,2012-2024,140,257,21,11736,254,49.72,20762,56.52,31,61,12,1280,44,2012,2024,ENG
45,Inzamam-ul-Haq,1992-2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,ICC/PAK
46,M Labuschagne,2018-2024,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024,AUS
47,FMM Worrell,1948-1963,51,87,9,3860,261,49.48,488,40.16,9,22,11,240+,11,1948,1963,WI
48,CP Mead,1911-1928,17,26,2,1185,182,49.37,619,30.04,4,3,3,38+,0,1911,1928,ENG
49,V Sehwag,2001-2013,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,ICC/IND
50,Abid Ali,2019-2021,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,2019,2021,PAK
51,V Kohli,2011-2024,113,191,11,8848,254,49.15,15924,55.56,29,30,14,991,26,2011,2024,IND
53,KC Bland,1961-1966,21,39,5,1669,144,49.08,885,37.74,3,9,2,123+,20,1961,1966,SA
54,B Mitchell,1929-1949,42,80,9,3471,189,48.88,158,29.11,8,21,3,41+,1,1929,1949,SA
56,TT Samaraweera,2001-2013,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,SL
57,RN Harvey,1948-1963,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427+,1,1948,1963,AUS
58,KD Walters,1965-1981,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525+,23,1965,1981,AUS
59,GC Smith,2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA
60,WH Ponsford,1924-1934,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119+,0,1924,1934,AUS
61,SJ McCabe,1930-1938,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241+,5+,1930,1938,AUS
62,DR Jardine,1928-1934,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53+,0,1928,1934,ENG

In [59]:
df['Balls_Faced'] = df['Balls_Faced'].astype('int')

In [60]:
df.dtypes

Player                  object
Span                    object
Matches                  int32
Inns                     int64
Not_Outs                 int64
Runs                     int64
Highest_Inns_Score       int32
Ave                    float64
Balls_Faced              int32
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Rookie_Year              int32
Final_Year               int32
Country                 object
dtype: object

In [61]:
df['4s'] = df['4s'].str.split(pat = '+').str[0]

In [63]:
df['6s'] = df['6s'].str.split(pat = '+').str[0]

In [66]:
df['4s'] = df['4s'].astype('int')

In [67]:
df['6s'] = df['6s'].astype('int')

In [68]:
df.dtypes

Player                  object
Span                    object
Matches                  int32
Inns                     int64
Not_Outs                 int64
Runs                     int64
Highest_Inns_Score       int32
Ave                    float64
Balls_Faced              int32
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                       int32
6s                       int32
Rookie_Year              int32
Final_Year               int32
Country                 object
dtype: object

In [71]:
df['Career_Length'] = df['Final_Year'] - df['Rookie_Year']

In [72]:
df

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country,Career_Length
0,DG Bradman,1928-1948,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,1928,1948,AUS,20
1,HC Brook,2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023,ENG,1
2,AC Voges,2015-2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS,1
3,RG Pollock,1963-1970,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,1963,1970,SA,7
4,GA Headley,1930-1954,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,1930,1954,WI,24
6,H Sutcliffe,1924-1935,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,1924,1935,ENG,11
7,E Paynter,1931-1939,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,1931,1939,ENG,8
8,KF Barrington,1955-1968,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,1955,1968,ENG,13
10,WR Hammond,1927-1947,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,1927,1947,ENG,20
11,GS Sobers,1954-1974,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593,32,1954,1974,WI,20
13,SPD Smith,2010-2024,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024,AUS,14
14,JB Hobbs,1908-1930,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8,1908,1930,ENG,22
16,L Hutton,1937-1955,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7,1937,1955,ENG,18
17,JH Kallis,1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,ICC/SA,18
18,GE Tyldesley,1921-1929,14,20,2,990,122,55.00,178,29.21,3,6,2,37,2,1921,1929,ENG,8
19,KS Williamson,2010-2024,100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24,2010,2024,NZ,14
20,CA Davis,1968-1973,15,29,5,1301,183,54.20,665,35.48,4,4,1,65,1,1968,1973,WI,5
21,VG Kambli,1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,IND,2
22,GS Chappell,1970-1984,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,1970,1984,AUS,14
23,AD Nourse,1935-1951,34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6,1935,1951,SA,16
24,SR Tendulkar,1989-2013,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058,69,1989,2013,IND,24
25,BC Lara,1990-2006,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006,ICC/WI,16
26,Javed Miandad,1976-1993,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788,48,1976,1993,PAK,17
27,R Dravid,1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,ICC/IND,16
28,Mohammad Yousuf,1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,PAK,12
29,Younis Khan,2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,PAK,17
30,RT Ponting,1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,AUS,17
31,J Ryder,1920-1929,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102,3,1920,1929,AUS,9
32,A Flower,1992-2002,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,1992,2002,ZIM,10
33,MEK Hussey,2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,AUS,8
34,S Chanderpaul,1994-2015,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015,WI,21
35,SM Gavaskar,1971-1987,125,214,16,10122,236,51.12,14184,43.35,34,45,12,908,26,1971,1987,IND,16
36,SR Waugh,1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,AUS,19
37,ML Hayden,1994-2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,AUS,15
38,AB de Villiers,2004-2018,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,SA,14
39,AR Border,1978-1994,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,1978,1994,AUS,16
40,DJ Mitchell,2019-2024,23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29,2019,2024,NZ,5
41,IVA Richards,1974-1991,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952,84,1974,1991,WI,17
42,DCS Compton,1937-1957,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342,3,1937,1957,ENG,20
43,DPMD Jayawardene,1997-2014,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,SL,17
44,JE Root,2012-2024,140,257,21,11736,254,49.72,20762,56.52,31,61,12,1280,44,2012,2024,ENG,12
45,Inzamam-ul-Haq,1992-2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,ICC/PAK,15
46,M Labuschagne,2018-2024,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024,AUS,6
47,FMM Worrell,1948-1963,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11,1948,1963,WI,15
48,CP Mead,1911-1928,17,26,2,1185,182,49.37,619,30.04,4,3,3,38,0,1911,1928,ENG,17
49,V Sehwag,2001-2013,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,ICC/IND,12
50,Abid Ali,2019-2021,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,2019,2021,PAK,2
51,V Kohli,2011-2024,113,191,11,8848,254,49.15,15924,55.56,29,30,14,991,26,2011,2024,IND,13
53,KC Bland,1961-1966,21,39,5,1669,144,49.08,885,37.74,3,9,2,123,20,1961,1966,SA,5
54,B Mitchell,1929-1949,42,80,9,3471,189,48.88,158,29.11,8,21,3,41,1,1929,1949,SA,20
56,TT Samaraweera,2001-2013,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,SL,12
57,RN Harvey,1948-1963,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427,1,1948,1963,AUS,15
58,KD Walters,1965-1981,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,1965,1981,AUS,16
59,GC Smith,2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA,12
60,WH Ponsford,1924-1934,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,1924,1934,AUS,10
61,SJ McCabe,1930-1938,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,1930,1938,AUS,8
62,DR Jardine,1928-1934,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,1928,1934,ENG,6

In [73]:
df['Career_Length'].mean()

13.298245614035087

In [75]:
df[df['Career_Length'] > 10]['Batting_Strike_Rate'].mean()

49.98875

In [79]:
df[df['Rookie_Year'] < 1960]['Player'].count()

20

In [83]:
df.groupby('Country')['Highest_Inns_Score'].max().to_frame('Highinncountry').reset_index().sort_values('Highinncountry', ascending = False)

    Country  Highinncountry
5    ICC/WI             400
0       AUS             380
10       SL             374
11       WI             365
1       ENG             364
3   ICC/PAK             329
2   ICC/IND             319
8       PAK             313
9        SA             278
4    ICC/SA             277
6       IND             254
7        NZ             251
12      ZIM             232